"use client"

import { Navigation } from "@/components/navigation"
import { Footer } from "@/components/footer"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Progress } from "@/components/ui/progress"
import {
  Swords, FileDown, AlertTriangle, AlertCircle, CheckCircle,
  MessageSquare, Bot, Brain, Activity, Star, Package, Headphones, Sparkles, Languages
} from "lucide-react"
import { AreaChart, Area, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer, ReferenceLine } from "recharts"

const topStats = [
  { label: "Total Reviews", value: "210", icon: MessageSquare },
  { label: "Bot Flagged", value: "14", icon: Bot },
  { label: "Sarcasm Queued", value: "6", icon: Sparkles },
  { label: "Languages", value: "2", icon: Languages },
]

const featureScores = [
  { name: "Battery", score: 80, status: "green", confidence: 94 },
  { name: "Camera", score: 74, status: "green", confidence: 91 },
  { name: "Performance", score: 77, status: "green", confidence: 89 },
  { name: "Display", score: 72, status: "green", confidence: 92 },
  { name: "Sound", score: 73, status: "green", confidence: 88 },
  { name: "Build", score: 70, status: "yellow", confidence: 85 },
  { name: "Packaging", score: 56, status: "red", alert: true, confidence: 96 },
]

const alerts = [
  {
    type: "critical",
    icon: AlertTriangle,
    title: "Packaging Velocity Alert",
    message: "Complaints at 50% — Escalate to Courier Partner",
  },
  {
    type: "warning",
    icon: AlertCircle,
    title: "Build Quality Watch",
    message: "Declining mentions across headphones category",
  },
  {
    type: "success",
    icon: CheckCircle,
    title: "Battery Performing Well",
    message: "Stable positive sentiment across all products",
  },
]

const products = [
  { name: "Smartphone", rating: 3.41, reviews: 100, icon: Package },
  { name: "Headphones", rating: 3.56, reviews: 55, icon: Headphones },
  { name: "Face Cream", rating: 3.64, reviews: 55, icon: Sparkles },
]

const trendData = [
  { month: "Jan", rate: 2.5 },
  { month: "Feb", rate: 6.0 },
  { month: "Mar", rate: 37.8 },
  { month: "Apr", rate: 50.0 },
]

function downloadReport() {
  const reportContent = `
SIGNALAHEAD - WAR ROOM INTELLIGENCE REPORT
Generated: ${new Date().toLocaleString()}
==========================================

EXECUTIVE SUMMARY
-----------------
Total Reviews Analyzed: 210
Products Monitored: 3 (Smartphone, Headphones, Face Cream)
Bot/Spam Reviews Flagged: 14
Sarcastic Reviews Queued: 6
Languages Processed: English, Hindi

CRITICAL ALERTS
---------------
1. PACKAGING VELOCITY ALERT (CRITICAL)
   - Current complaint rate: 50%
   - Threshold: 25%
   - Status: BREACHED
   - Root Cause: Transit moisture damage during last-mile courier handling
   - Escalate To: Courier Partner (NOT QC Team)
   - Recommended Action: Review courier SLA, add weatherproof packaging

2. Build Quality Watch (Warning)
   - Declining mentions across headphones category
   - Monitor over next 2 weeks

FEATURE HEALTH SCORECARD
------------------------
Battery:      80% (Confidence: 94%) - HEALTHY
Camera:       74% (Confidence: 91%) - HEALTHY
Performance:  77% (Confidence: 89%) - HEALTHY
Display:      72% (Confidence: 92%) - HEALTHY
Sound:        73% (Confidence: 88%) - HEALTHY
Build:        70% (Confidence: 85%) - WATCH
Packaging:    56% (Confidence: 96%) - CRITICAL

COMPETITIVE INTELLIGENCE (RADAR ENGINE)
---------------------------------------
Packaging: YOUR PROBLEM (Competitor at 71% vs Your 56%)
Battery: INDUSTRY-WIDE (Both brands ~80%)

PRODUCT RATINGS
---------------
Smartphone:   3.41/5 (100 reviews)
Headphones:   3.56/5 (55 reviews)
Face Cream:   3.64/5 (55 reviews)

---
Report generated by SignalAhead Intelligence Platform
Signal Squad | Hack Malenadu '26
  `.trim()

  const blob = new Blob([reportContent], { type: 'text/plain' })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = `SignalAhead_Report_${new Date().toISOString().split('T')[0]}.txt`
  document.body.appendChild(a)
  a.click()
  document.body.removeChild(a)
  URL.revokeObjectURL(url)
}

export default function DashboardPage() {
  return (
    <div className="min-h-screen bg-background">
      <Navigation />
      
      <main className="pt-24 pb-16">
        <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
          {/* Header */}
          <div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between">
            <div>
              <div className="flex items-center gap-3">
                <div className="flex h-10 w-10 items-center justify-center rounded-lg bg-gradient-to-br from-orange-500 to-orange-600">
                  <Swords className="h-5 w-5 text-white" />
                </div>
                <h1 className="text-3xl font-bold tracking-tight text-foreground sm:text-4xl">
                  War Room Dashboard
                </h1>
              </div>
              <p className="mt-2 text-muted-foreground">
                SignalAhead Intelligence &middot; 210 reviews processed &middot; 3 products
              </p>
            </div>
            <Button onClick={downloadReport} className="bg-foreground hover:bg-foreground/90 text-background">
              <FileDown className="mr-2 h-4 w-4" />
              Download Report
            </Button>
          </div>

          {/* Top Stats */}
          <div className="mt-8 grid grid-cols-2 gap-4 sm:grid-cols-4">
            {topStats.map((stat) => (
              <Card key={stat.label} className="border-border">
                <CardContent className="flex items-center gap-4 pt-6">
                  <div className="flex h-12 w-12 items-center justify-center rounded-xl bg-orange-50">
                    <stat.icon className="h-6 w-6 text-orange-500" />
                  </div>
                  <div>
                    <div className="font-mono text-3xl font-bold text-foreground">
                      {stat.value}
                    </div>
                    <div className="text-sm text-muted-foreground">{stat.label}</div>
                  </div>
                </CardContent>
              </Card>
            ))}
          </div>

          {/* Main Grid */}
          <div className="mt-8 grid gap-6 lg:grid-cols-3">
            {/* Feature Health Scorecard */}
            <div className="lg:col-span-2">
              <Card>
                <CardHeader>
                  <CardTitle>Feature Health Scorecard</CardTitle>
                  <CardDescription>Sentiment scores with confidence levels across all product attributes</CardDescription>
                </CardHeader>
                <CardContent className="space-y-4">
                  {featureScores.map((feature) => (
                    <div key={feature.name} className="flex items-center gap-4">
                      <div className="w-24 text-sm font-medium text-foreground flex items-center gap-2">
                        {feature.name}
                        {feature.alert && (
                          <span className="relative flex h-2 w-2">
                            <span className="absolute inline-flex h-full w-full animate-ping rounded-full bg-red-400 opacity-75" />
                            <span className="relative inline-flex h-2 w-2 rounded-full bg-red-500" />
                          </span>
                        )}
                      </div>
                      <div className="flex-1">
                        <Progress
                          value={feature.score}
                          className={`h-3 ${
                            feature.status === "green"
                              ? "[&>div]:bg-green-500"
                              : feature.status === "yellow"
                              ? "[&>div]:bg-amber-500"
                              : "[&>div]:bg-red-500"
                          }`}
                        />
                      </div>
                      <div className="w-24 flex items-center gap-2">
                        <span
                          className={`font-mono text-sm font-bold ${
                            feature.status === "green"
                              ? "text-green-600"
                              : feature.status === "yellow"
                              ? "text-amber-600"
                              : "text-red-600"
                          }`}
                        >
                          {feature.score}%
                        </span>
                        <span className="text-xs text-muted-foreground">
                          ({feature.confidence}%)
                        </span>
                      </div>
                    </div>
                  ))}
                </CardContent>
              </Card>
            </div>

            {/* Active Alerts */}
            <div>
              <Card>
                <CardHeader>
                  <CardTitle>Active Alerts</CardTitle>
                </CardHeader>
                <CardContent className="space-y-3">
                  {alerts.map((alert, i) => (
                    <div
                      key={i}
                      className={`rounded-lg p-3 ${
                        alert.type === "critical"
                          ? "bg-red-50 border border-red-200"
                          : alert.type === "warning"
                          ? "bg-amber-50 border border-amber-200"
                          : "bg-green-50 border border-green-200"
                      }`}
                    >
                      <div className="flex items-start gap-3">
                        <alert.icon
                          className={`h-5 w-5 shrink-0 mt-0.5 ${
                            alert.type === "critical"
                              ? "text-red-600"
                              : alert.type === "warning"
                              ? "text-amber-600"
                              : "text-green-600"
                          }`}
                        />
                        <div>
                          <div className={`text-sm font-semibold ${
                            alert.type === "critical"
                              ? "text-red-700"
                              : alert.type === "warning"
                              ? "text-amber-700"
                              : "text-green-700"
                          }`}>
                            {alert.title}
                          </div>
                          <p className="text-sm text-muted-foreground mt-0.5">{alert.message}</p>
                        </div>
                      </div>
                    </div>
                  ))}
                </CardContent>
              </Card>
            </div>
          </div>

          {/* Second Row */}
          <div className="mt-6 grid gap-6 lg:grid-cols-3">
            {/* Products */}
            <div>
              <Card>
                <CardHeader>
                  <CardTitle>Products Overview</CardTitle>
                  <CardDescription>3 categories monitored</CardDescription>
                </CardHeader>
                <CardContent className="space-y-4">
                  {products.map((product) => (
                    <div
                      key={product.name}
                      className="flex items-center gap-4 rounded-lg bg-secondary/50 p-3"
                    >
                      <div className="flex h-10 w-10 items-center justify-center rounded-lg bg-background border border-border">
                        <product.icon className="h-5 w-5 text-orange-500" />
                      </div>
                      <div className="flex-1">
                        <div className="font-medium text-foreground">{product.name}</div>
                        <div className="flex items-center gap-2 text-sm text-muted-foreground">
                          <Star className="h-3 w-3 fill-amber-400 text-amber-400" />
                          {product.rating} &middot; {product.reviews} reviews
                        </div>
                      </div>
                    </div>
                  ))}
                </CardContent>
              </Card>
            </div>

            {/* Packaging Trend */}
            <div className="lg:col-span-2">
              <Card className="border-orange-200">
                <CardHeader>
                  <CardTitle className="text-orange-600">Packaging Trend (Velocity Engine)</CardTitle>
                  <CardDescription>Complaint rate velocity over time — threshold at 25%</CardDescription>
                </CardHeader>
                <CardContent>
                  <div className="h-[200px] w-full">
                    <ResponsiveContainer width="100%" height="100%">
                      <AreaChart data={trendData} margin={{ top: 10, right: 10, bottom: 0, left: 0 }}>
                        <defs>
                          <linearGradient id="trendGradient" x1="0" y1="0" x2="0" y2="1">
                            <stop offset="5%" stopColor="#ea580c" stopOpacity={0.3} />
                            <stop offset="95%" stopColor="#ea580c" stopOpacity={0} />
                          </linearGradient>
                        </defs>
                        <CartesianGrid strokeDasharray="3 3" stroke="#e5e7eb" />
                        <XAxis dataKey="month" stroke="#9ca3af" tick={{ fill: '#6b7280', fontSize: 11 }} />
                        <YAxis stroke="#9ca3af" tick={{ fill: '#6b7280', fontSize: 11 }} tickFormatter={(v) => `${v}%`} />
                        <Tooltip
                          contentStyle={{
                            backgroundColor: '#fff',
                            border: '1px solid #e5e7eb',
                            borderRadius: '8px',
                          }}
                          formatter={(value: number) => [`${value}%`, 'Complaint Rate']}
                        />
                        <ReferenceLine y={25} stroke="#ef4444" strokeDasharray="3 3" />
                        <Area type="monotone" dataKey="rate" stroke="#ea580c" strokeWidth={2} fill="url(#trendGradient)" />
                      </AreaChart>
                    </ResponsiveContainer>
                  </div>
                </CardContent>
              </Card>
            </div>
          </div>

          {/* Bottom Row - Engine Summaries */}
          <div className="mt-6 grid gap-6 sm:grid-cols-2">
            {/* Autopsy Summary */}
            <Card className="border-purple-200 bg-purple-50/30">
              <CardContent className="flex items-start gap-4 pt-6">
                <div className="flex h-12 w-12 shrink-0 items-center justify-center rounded-xl bg-purple-100">
                  <Brain className="h-6 w-6 text-purple-600" />
                </div>
                <div>
                  <div className="text-sm font-medium text-purple-600">Autopsy Engine</div>
                  <div className="mt-1 font-semibold text-foreground">
                    Probable Cause: Transit moisture damage
                  </div>
                  <div className="mt-1 text-sm text-muted-foreground">
                    Escalate to: <span className="font-medium text-purple-700">Courier Partner</span>
                  </div>
                  <Badge className="mt-2 bg-purple-100 text-purple-700 border-purple-200">84% Confidence</Badge>
                </div>
              </CardContent>
            </Card>

            {/* Radar Summary */}
            <Card className="border-teal-200 bg-teal-50/30">
              <CardContent className="flex items-start gap-4 pt-6">
                <div className="flex h-12 w-12 shrink-0 items-center justify-center rounded-xl bg-teal-100">
                  <Activity className="h-6 w-6 text-teal-600" />
                </div>
                <div>
                  <div className="text-sm font-medium text-teal-600">Radar Engine</div>
                  <div className="mt-2 flex flex-wrap gap-2">
                    <Badge className="bg-red-100 text-red-700 border-red-200">Packaging: YOUR ISSUE</Badge>
                    <Badge className="bg-amber-100 text-amber-700 border-amber-200">Battery: INDUSTRY-WIDE</Badge>
                  </div>
                  <div className="mt-2 text-sm text-muted-foreground">
                    Competitor packaging at 71% vs your 56%
                  </div>
                </div>
              </CardContent>
            </Card>
          </div>
        </div>
      </main>

      <Footer />
    </div>
  )
}
